title: Ij.start.canòn | Setup Canòn
description: The Ij.start.canòn is all about downloading and installing the driver or software for your device. The driver is the link between the device and the canòn Ij printer.
